import { Ionicons } from '@expo/vector-icons';
import { Colors } from './colors';

/**
 * Administrative Journey Engine data.
 *
 * Each "journey" represents a goal someone living in France is trying to reach
 * (e.g. getting a residence permit). A journey is a sequence of concrete steps,
 * each with a purpose, estimated duration, required documents, where to go, the
 * official organization, plain-language instructions, common mistakes, what
 * happens next and a link to the official source.
 */

export type JourneyId =
  | 'asylum'
  | 'student'
  | 'residence'
  | 'caf'
  | 'health'
  | 'work'
  | 'arrived'
  | 'nationality'
  | 'other';

export interface JourneyStep {
  id: string;
  title: string;
  /** One short sentence: why this step matters. */
  purpose: string;
  /** Human estimate, e.g. "1–2 weeks". */
  duration: string;
  /** Required documents for this step. */
  documents: string[];
  /** Where to do it (online portal, office...). */
  whereToGo: string;
  /** Official organization. */
  organization: string;
  /** Official government / institution URL. */
  officialUrl: string;
  /** Plain-language numbered instructions. */
  instructions: string[];
  /** 2–3 things people commonly get wrong. */
  commonMistakes: string[];
  /** One sentence: what to expect after completing this step. */
  whatNext: string;
}

export interface Journey {
  id: JourneyId;
  title: string;
  subtitle: string;
  icon: keyof typeof Ionicons.glyphMap;
  accent: string;
  steps: JourneyStep[];
}

export const JOURNEYS: Journey[] = [
  {
    id: 'arrived',
    title: 'Just arrived in France',
    subtitle: 'The essential first steps after you land',
    icon: 'airplane-outline',
    accent: Colors.blue,
    steps: [
      {
        id: 'arr-1',
        title: 'Validate your visa (VLS-TS)',
        purpose: 'Most long-stay visas must be validated online within 3 months of arrival, or they become invalid.',
        duration: '30 minutes',
        documents: ['Passport', 'Long-stay visa', 'French address', 'Bank card for the tax stamp'],
        whereToGo: 'Online — anef.administration-etrangers.interieur.gouv.fr',
        organization: 'Ministère de l’Intérieur',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Go to the official ANEF website and choose “Je valide mon visa de long séjour”.',
          'Create an account or log in with your email.',
          'Enter your visa number, date of entry and French address.',
          'Pay the tax stamp (timbre fiscal) online with your bank card.',
          'Download and save the confirmation PDF.',
        ],
        commonMistakes: [
          'Waiting longer than 3 months after arrival.',
          'Entering the wrong date of entry into France.',
          'Forgetting to keep the validation confirmation.',
        ],
        whatNext: 'Your visa now acts as a residence permit for its full duration — keep the confirmation safe.',
      },
      {
        id: 'arr-2',
        title: 'Open a French bank account',
        purpose: 'You need an account (RIB) for rent, salary, CAF and almost every administrative step.',
        duration: '1–2 weeks',
        documents: ['Passport / ID', 'Proof of address', 'Visa or residence permit'],
        whereToGo: 'A bank branch or an online bank',
        organization: 'Your chosen bank',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N99',
        instructions: [
          'Choose a bank (traditional branch or online bank like a neobank).',
          'Book an appointment or sign up online.',
          'Provide your ID, proof of address and visa/permit.',
          'Receive your RIB (bank details) and card by post.',
        ],
        commonMistakes: [
          'Not having a proof of address yet — sort that first.',
          'Choosing a bank with high fees for non-residents.',
        ],
        whatNext: 'You’ll get a RIB you can give to your employer, landlord and CAF.',
      },
      {
        id: 'arr-3',
        title: 'Get proof of address (justificatif de domicile)',
        purpose: 'Almost every French procedure asks for a recent proof that you live somewhere.',
        duration: 'Same day',
        documents: ['Rental contract or hosting attestation', 'Utility bill (electricity, internet)'],
        whereToGo: 'Your landlord / utility provider',
        organization: 'EDF, internet provider, or host',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/F14807',
        instructions: [
          'If you rent: keep your rental contract and a recent utility bill.',
          'If hosted: ask your host for an “attestation d’hébergement” + their ID + a bill.',
          'Make sure the document is less than 3 months old.',
        ],
        commonMistakes: [
          'Using a document older than 3 months.',
          'Forgetting the host’s ID with the hosting attestation.',
        ],
        whatNext: 'You can now complete almost any other administrative step.',
      },
      {
        id: 'arr-4',
        title: 'Register for health insurance',
        purpose: 'Register with Assurance Maladie for reimbursed healthcare (PUMa online or CPAM in person).',
        duration: '1–4 months',
        documents: ['Passport', 'Visa / residence permit', 'Birth certificate (translated)', 'RIB', 'Proof of address'],
        whereToGo: 'ameli.fr → “Je n’ai pas de numéro de Sécurité sociale”, or your CPAM office',
        organization: 'CPAM / Assurance Maladie',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Go to ameli.fr and choose “Je n’ai pas de numéro de Sécurité sociale”, or visit your CPAM in person.',
          'Gather ID, visa/permit, translated birth certificate, RIB and proof of address.',
          'A temporary number (NIA) usually arrives in 1–4 weeks; attestation downloadable on ameli.fr in 1–2 months.',
          'Order your Carte Vitale from Ameli once registered — physical card in 2–4 months.',
        ],
        commonMistakes: [
          'Sending an untranslated birth certificate.',
          'Forgetting the RIB, which delays reimbursements.',
          'Not downloading the attestation while waiting for the Carte Vitale.',
        ],
        whatNext: 'You’ll have coverage proof (attestation) and can declare a médecin traitant.',
      },
    ],
  },
  {
    id: 'residence',
    title: 'Residence permit',
    subtitle: 'Apply for or renew your titre de séjour',
    icon: 'card-outline',
    accent: Colors.red,
    steps: [
      {
        id: 'res-1',
        title: 'Create your ANEF account',
        purpose: 'All residence-permit applications and renewals are handled online on the ANEF portal.',
        duration: '20 minutes',
        documents: ['Email address', 'Passport'],
        whereToGo: 'anef.administration-etrangers.interieur.gouv.fr',
        organization: 'ANEF / Préfecture',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Go to anef.administration-etrangers.interieur.gouv.fr (also listed on demarchesetrangers.fr).',
          'Click “Créer un compte” and enter your email and password.',
          'Confirm your email via the link they send you.',
          'Log in and start a new demande or renewal of titre de séjour.',
        ],
        commonMistakes: [
          'Using an email you can’t access later.',
          'Creating several accounts by mistake.',
          'Using outdated portal URLs — always use the ANEF link above.',
        ],
        whatNext: 'You can now prepare and submit your online application.',
      },
      {
        id: 'res-2',
        title: 'Prepare your supporting documents',
        purpose: 'A complete file avoids rejection; renewals must be filed on time with all 2026 requirements.',
        duration: '1–2 weeks',
        documents: [
          'Passport',
          'Proof of address < 6 months',
          'ePhoto code',
          'Proof of resources',
          'Current permit (if renewal)',
          'French language certificate (A2 or B1 — see instructions)',
          'Civic test certificate (test civique)',
        ],
        whereToGo: 'At home — scan everything as PDF',
        organization: 'Préfecture',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N110',
        instructions: [
          'For renewals: apply between 4 months and 2 months before your permit expires (not 3 months).',
          'Check the document list for your specific permit type on service-public.fr.',
          'Pass the mandatory French test: A2 for carte de séjour pluriannuelle, B1 for carte de résident (2026 rule).',
          'Pass the mandatory civic knowledge test (test civique) and keep your certificate.',
          'Scan each document clearly as a separate PDF and get an ePhoto code from an approved booth.',
        ],
        commonMistakes: [
          'Applying too early (more than 4 months before expiry) or too late (less than 2 months).',
          'Missing the language or civic test certificates required since 2026.',
          'Blurry scans or proof of address older than 6 months.',
        ],
        whatNext: 'With tests passed and documents scanned, you can submit on ANEF.',
      },
      {
        id: 'res-3',
        title: 'Submit the online application',
        purpose: 'This officially starts your request; the préfecture has a 55-day processing target (plan Nuñez, April 2026).',
        duration: '1 hour',
        documents: ['Completed ANEF form', 'All scanned documents', 'Language & civic test certificates'],
        whereToGo: 'ANEF online portal',
        organization: 'Préfecture',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Log into ANEF and open your draft application.',
          'Fill every section and upload your PDFs (including test certificates).',
          'Review carefully, then submit.',
          'Save the submission confirmation and note the date — processing target is 55 days.',
        ],
        commonMistakes: [
          'Submitting with a document or test certificate missing.',
          'Typos in passport number or dates.',
          'Assuming silence means approval — see the next steps.',
        ],
        whatNext: 'The préfecture reviews your file and issues a récépissé while processing.',
      },
      {
        id: 'res-4',
        title: 'Get your récépissé',
        purpose: 'A receipt proving your legal stay while the permit is processed (target: 55 days).',
        duration: '2–4 weeks (récépissé); up to 55 days total processing',
        documents: ['Application confirmation'],
        whereToGo: 'ANEF account / by post',
        organization: 'Préfecture',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Check your ANEF messages regularly.',
          'Download the récépissé when it appears and print it.',
          'Keep it with your passport at all times.',
          'If you receive no decision after 4 months, this counts as an implicit rejection (not approval) — follow up or appeal.',
        ],
        commonMistakes: [
          'Not checking ANEF notifications.',
          'Letting the récépissé expire without renewing it.',
          'Believing that no answer after 4 months means your permit is approved.',
        ],
        whatNext: 'You can legally stay (and often work) while you wait for the card.',
      },
      {
        id: 'res-5',
        title: 'Collect your residence permit',
        purpose: 'Pick up the physical card once approved and pay the timbre fiscal.',
        duration: 'Up to 55 days (processing target); card pickup when notified',
        documents: ['Récépissé', 'Passport', 'Timbre fiscal (tax stamp)'],
        whereToGo: 'Your local préfecture or as instructed on ANEF',
        organization: 'Préfecture',
        officialUrl: 'https://www.demarchesetrangers.fr',
        instructions: [
          'Wait for the ANEF message saying your card is ready.',
          'Buy the timbre fiscal online: €350 for a first card, €250 for a renewal (rates since 1 May 2026).',
          'Book a pickup appointment if required.',
          'Collect the card in person with your passport and payment proof.',
        ],
        commonMistakes: [
          'Arriving without having paid the correct timbre fiscal amount.',
          'Missing the pickup appointment window.',
          'Using outdated stamp amounts from before May 2026.',
        ],
        whatNext: 'You now hold your residence permit — note its expiry and renew between 4 and 2 months before.',
      },
    ],
  },
  {
    id: 'student',
    title: 'International student',
    subtitle: 'Study, residence and student life setup',
    icon: 'school-outline',
    accent: '#7B61FF',
    steps: [
      {
        id: 'stu-1',
        title: 'Validate your student visa',
        purpose: 'Required within 3 months to stay legally as a student.',
        duration: '30 minutes',
        documents: ['Passport', 'VLS-TS student visa', 'Address', 'Tax stamp'],
        whereToGo: 'anef.administration-etrangers.interieur.gouv.fr',
        organization: 'Ministère de l’Intérieur',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Open the visa validation portal.',
          'Enter your visa and arrival details.',
          'Pay the tax stamp online.',
          'Save the confirmation.',
        ],
        commonMistakes: ['Missing the 3-month deadline.', 'Wrong arrival date.'],
        whatNext: 'Your visa is now valid as a residence permit for the year.',
      },
      {
        id: 'stu-2',
        title: 'Enrol / confirm your registration',
        purpose: 'Get your student certificate (certificat de scolarité), needed for many steps.',
        duration: '1 week',
        documents: ['Admission letter', 'Passport', 'Photos'],
        whereToGo: 'Your university registration office',
        organization: 'Your university',
        officialUrl: 'https://www.campusfrance.org/en',
        instructions: [
          'Bring your admission letter and ID to the registration office.',
          'Pay any tuition / CVEC fee if required.',
          'Collect your student card and certificat de scolarité.',
        ],
        commonMistakes: ['Forgetting to pay the CVEC contribution.', 'Missing enrolment deadlines.'],
        whatNext: 'You can use your student certificate for health insurance and CAF.',
      },
      {
        id: 'stu-3',
        title: 'Register with student health insurance',
        purpose: 'Free social security registration for students.',
        duration: '2–4 weeks',
        documents: ['Passport', 'Visa', 'Certificat de scolarité', 'RIB'],
        whereToGo: 'etudiant-etranger.ameli.fr',
        organization: 'Assurance Maladie',
        officialUrl: 'https://etudiant-etranger.ameli.fr',
        instructions: [
          'Go to the dedicated student registration site.',
          'Create an account and upload your documents.',
          'Add your RIB for reimbursements.',
          'Wait for your social security number.',
        ],
        commonMistakes: ['Uploading low-quality scans.', 'Forgetting the RIB.'],
        whatNext: 'Once registered, you can order your Carte Vitale.',
      },
      {
        id: 'stu-4',
        title: 'Apply for CAF housing aid',
        purpose: 'Reduce your rent with APL, ALF, or ALS — CAF assigns the most beneficial automatically.',
        duration: '1 month',
        documents: ['RIB', 'Rental contract (bail)', 'Passport', 'Birth certificate', 'Social security number'],
        whereToGo: 'caf.fr (online-only; FranceConnect available)',
        organization: 'CAF',
        officialUrl: 'https://www.caf.fr',
        instructions: [
          'Create your account on caf.fr online — no paper Cerfa 10840.',
          'Start a housing aid request; CAF assigns APL, ALF, or ALS automatically.',
          'Enter rent, landlord and income details. In colocation, each tenant applies separately.',
          'Aid is not paid for the first month (mois de carence); payments are normally on the 5th.',
        ],
        commonMistakes: [
          'Expecting aid in the first month of the lease.',
          'One colocataire applying for everyone instead of separate files.',
          'Entering rent or income incorrectly.',
        ],
        whatNext: 'CAF reviews your file; income is recalculated every 3 months.',
      },
    ],
  },
  {
    id: 'caf',
    title: 'CAF benefits',
    subtitle: 'Housing aid (APL, ALF, ALS), family and activity benefits',
    icon: 'home-outline',
    accent: Colors.success,
    steps: [
      {
        id: 'caf-1',
        title: 'Create your CAF account',
        purpose: 'Registration is online-only on caf.fr — the paper Cerfa 10840 is no longer used for most people.',
        duration: '20 minutes',
        documents: ['Passport / residence permit', 'Email', 'RIB'],
        whereToGo: 'caf.fr (FranceConnect login available)',
        organization: 'CAF',
        officialUrl: 'https://www.caf.fr',
        instructions: [
          'Go to caf.fr and choose “Se connecter / S’inscrire”.',
          'You can sign in with FranceConnect or create a CAF account directly.',
          'Register as a new allocataire online — no paper form needed.',
          'Fill in your personal and banking (RIB) details.',
        ],
        commonMistakes: [
          'Trying to submit a paper Cerfa 10840 — registration is online-only.',
          'Using inconsistent name spelling vs your ID.',
          'Skipping the RIB.',
        ],
        whatNext: 'You get an allocataire number to manage your benefits online.',
      },
      {
        id: 'caf-2',
        title: 'Get your social security number',
        purpose: 'CAF needs your numéro de Sécurité sociale to process your file.',
        duration: '2–6 weeks',
        documents: ['Birth certificate (translated)', 'Passport', 'Visa / permit'],
        whereToGo: 'ameli.fr or your local CPAM',
        organization: 'CPAM',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Register with CPAM if you haven’t already (online at ameli.fr or in person).',
          'Provide your translated birth certificate.',
          'Wait for your permanent social security number.',
          'Add it to your CAF profile on caf.fr.',
        ],
        commonMistakes: ['Untranslated birth certificate.', 'Not following up with CPAM if delayed.'],
        whatNext: 'With the number added, CAF can finalise your housing aid file.',
      },
      {
        id: 'caf-3',
        title: 'Submit your housing aid request',
        purpose: 'CAF assigns the most beneficial aid: APL, ALF, or ALS — you do not choose.',
        duration: '1 hour',
        documents: ['RIB', 'Rental contract (bail)', 'Income details', 'Landlord details'],
        whereToGo: 'caf.fr — “Mon Compte”',
        organization: 'CAF',
        officialUrl: 'https://www.caf.fr',
        instructions: [
          'Log into your CAF account and start a housing aid request.',
          'Enter your rent, landlord, household and income details.',
          'CAF automatically assigns APL, ALF, or ALS — whichever is most beneficial.',
          'In shared housing (colocation), each tenant must apply separately with their own file.',
          'Note: the first month of rental never receives aid (mois de carence).',
        ],
        commonMistakes: [
          'Expecting payment in the first month of your lease.',
          'One person applying for the whole colocation instead of each tenant filing separately.',
          'Under/over-declaring income or rent.',
        ],
        whatNext: 'CAF reviews your file; payments start from the eligible month (not month one).',
      },
      {
        id: 'caf-4',
        title: 'Track payments and updates',
        purpose: 'Aid is recalculated every 3 months; rising income reduces your payment.',
        duration: 'Ongoing',
        documents: ['CAF account access'],
        whereToGo: 'caf.fr',
        organization: 'CAF',
        officialUrl: 'https://www.caf.fr',
        instructions: [
          'Housing aid is normally paid on the 5th of each month.',
          '2026 payment exceptions: 7 April, 6 July, 4 September, 4 December.',
          'Your income is recalculated automatically every 3 months — not once a year.',
          'Report moves, job changes or family changes promptly on caf.fr.',
        ],
        commonMistakes: [
          'Not reporting a pay rise — CAF will catch up and you may owe money back.',
          'Expecting the same payment date every month in 2026 (check the exceptions).',
          'Forgetting to update your situation after a move or colocation change.',
        ],
        whatNext: 'Your benefits stay accurate and payments continue on schedule.',
      },
    ],
  },
  {
    id: 'health',
    title: 'Health insurance',
    subtitle: 'Get covered with Assurance Maladie',
    icon: 'medkit-outline',
    accent: '#00E0B8',
    steps: [
      {
        id: 'hea-1',
        title: 'Register for health coverage',
        purpose: 'Choose the right path: employee DPAE, PUMa online, student portal, or AME if you have no titre de séjour.',
        duration: '1 hour',
        documents: ['Passport', 'Visa / permit (if applicable)', 'Birth certificate (translated)', 'Proof of address', 'RIB'],
        whereToGo: 'ameli.fr, etudiant-etranger.ameli.fr, or your CPAM office',
        organization: 'CPAM / Assurance Maladie',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Employees: your employer files the DPAE — registration with CPAM is usually automatic.',
          'Everyone else (PUMa): go to ameli.fr → “Je n’ai pas de numéro de Sécurité sociale”, or visit your CPAM in person.',
          'Students: use the separate portal at etudiant-etranger.ameli.fr (not the standard PUMa form).',
          'Without a titre de séjour: after 3 months in France you may apply for AME (Aide Médicale de l’État).',
        ],
        commonMistakes: [
          'Students using the standard PUMa form instead of etudiant-etranger.ameli.fr.',
          'Employees re-applying manually when the employer DPAE should handle it.',
          'Applying for PUMa before 3 months of stable residence (AME path if undocumented).',
        ],
        whatNext: 'CPAM opens your file and issues a temporary number (NIA) first.',
      },
      {
        id: 'hea-2',
        title: 'Receive your social security number',
        purpose: 'You get a temporary NIA first, then your permanent numéro de Sécurité sociale.',
        duration: 'NIA in 1–4 weeks; attestation on ameli.fr in 1–2 months',
        documents: ['Submitted registration file'],
        whereToGo: 'By post / your ameli.fr account',
        organization: 'CPAM',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'A temporary number (NIA) usually arrives within 1–4 weeks.',
          'Your permanent numéro de Sécurité sociale follows by post.',
          'Download your attestation de droits on ameli.fr within 1–2 months — use it until your Carte Vitale arrives.',
          'If delayed, contact your CPAM by phone or secure message.',
        ],
        commonMistakes: [
          'Not downloading the attestation while waiting for the physical card.',
          'Losing the letter with your permanent number.',
        ],
        whatNext: 'You can create your Ameli account and request your Carte Vitale.',
      },
      {
        id: 'hea-3',
        title: 'Create your Ameli account',
        purpose: 'Manage reimbursements, attestation and Carte Vitale requests online.',
        duration: '20 minutes',
        documents: ['Social security number (or NIA)', 'RIB'],
        whereToGo: 'ameli.fr',
        organization: 'Assurance Maladie',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Go to ameli.fr and click “Créer mon compte”.',
          'Enter your social security number or NIA.',
          'Add your RIB so reimbursements are paid directly to your bank.',
        ],
        commonMistakes: [
          'Entering the wrong social security number.',
          'Forgetting to add the RIB — reimbursements will be delayed.',
        ],
        whatNext: 'Request your Carte Vitale from your Ameli account.',
      },
      {
        id: 'hea-4',
        title: 'Order your Carte Vitale',
        purpose: 'The physical card makes reimbursements automatic at doctors and pharmacies.',
        duration: '2–4 months for the physical card',
        documents: ['ID photo (e-photo code)', 'ID document'],
        whereToGo: 'Your ameli.fr account',
        organization: 'Assurance Maladie',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'In your Ameli account, request the Carte Vitale.',
          'Upload a compliant e-photo and your ID.',
          'Use your attestation de droits (downloadable on ameli.fr) while you wait.',
          'The physical Carte Vitale usually arrives by post in 2–4 months.',
        ],
        commonMistakes: [
          'Non-compliant photo format.',
          'Not using the attestation during the waiting period.',
        ],
        whatNext: 'Present your Carte Vitale (or attestation) at any healthcare visit.',
      },
      {
        id: 'hea-5',
        title: 'Choose a médecin traitant',
        purpose: 'Declaring a GP (médecin traitant) gives you the best reimbursement rate.',
        duration: 'Same day',
        documents: ['Carte Vitale or attestation de droits'],
        whereToGo: 'Your chosen doctor’s office',
        organization: 'Assurance Maladie',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Find a généraliste (GP) accepting new patients.',
          'Ask them to declare you as their “médecin traitant”.',
          'They register it online with your Carte Vitale or attestation.',
          'Low income? Apply for CSS (Complémentaire Santé Solidaire) on ameli.fr — free or near-free mutuelle cover.',
        ],
        commonMistakes: [
          'Skipping médecin traitant declaration and getting reimbursed less.',
          'Not applying for CSS when on a low income.',
        ],
        whatNext: 'Your healthcare costs are reimbursed at the best rate; CSS covers what CPAM does not if eligible.',
      },
    ],
  },
  {
    id: 'work',
    title: 'Looking for work',
    subtitle: 'Right to work, registration and job search',
    icon: 'briefcase-outline',
    accent: Colors.warning,
    steps: [
      {
        id: 'wrk-1',
        title: 'Check your right to work',
        purpose: 'Confirm your residence permit or visa actually allows employment.',
        duration: '30 minutes',
        documents: ['Residence permit / visa'],
        whereToGo: 'Check your permit category online',
        organization: 'Préfecture',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/F2728',
        instructions: [
          'Look at the mention on your permit (e.g. “autorise à travailler”).',
          'Check the rules for your permit type.',
          'If unsure, ask the AI assistant below.',
        ],
        commonMistakes: ['Assuming all permits allow full-time work.', 'Ignoring student work-hour limits.'],
        whatNext: 'You know whether you can work and for how many hours.',
      },
      {
        id: 'wrk-2',
        title: 'Register with France Travail',
        purpose: 'Access job offers, advice and possible unemployment support.',
        duration: '1 week',
        documents: ['ID', 'Residence permit', 'RIB', 'CV'],
        whereToGo: 'francetravail.fr',
        organization: 'France Travail (ex Pôle emploi)',
        officialUrl: 'https://www.francetravail.fr',
        instructions: [
          'Create an account on francetravail.fr.',
          'Complete your profile and upload your CV.',
          'Attend your first appointment if scheduled.',
        ],
        commonMistakes: ['Incomplete profile.', 'Missing the first appointment.'],
        whatNext: 'You’ll receive tailored job offers and support.',
      },
      {
        id: 'wrk-3',
        title: 'Prepare a French CV & lettre de motivation',
        purpose: 'French applications follow a specific, expected format.',
        duration: '2–3 days',
        documents: ['Work history', 'Diplomas'],
        whereToGo: 'At home — use the AI tools',
        organization: 'PrefAI',
        officialUrl: 'https://www.francetravail.fr',
        instructions: [
          'List your experience and education.',
          'Use the AI Reply / Translate tools to draft in French.',
          'Keep the CV to one page where possible.',
        ],
        commonMistakes: ['Direct translation that sounds unnatural.', 'Too long, unfocused CV.'],
        whatNext: 'You have ready-to-send French application documents.',
      },
      {
        id: 'wrk-4',
        title: 'Get your social security & RIB ready',
        purpose: 'Employers need these to hire and pay you.',
        duration: '1–4 weeks',
        documents: ['Social security number', 'Bank RIB'],
        whereToGo: 'CPAM + your bank',
        organization: 'CPAM',
        officialUrl: 'https://www.ameli.fr',
        instructions: [
          'Make sure you have a social security number.',
          'Download your RIB from your bank app.',
          'Keep both ready to share with employers.',
        ],
        commonMistakes: ['Starting a job without a social security number.'],
        whatNext: 'You’re ready to sign a contract and get paid correctly.',
      },
    ],
  },
  {
    id: 'asylum',
    title: 'Asylum seeker',
    subtitle: 'Request international protection in France',
    icon: 'shield-outline',
    accent: Colors.blue,
    steps: [
      {
        id: 'asy-1',
        title: 'Go to a first-reception office (SPADA)',
        purpose: 'The SPADA is your entry point to register an asylum claim.',
        duration: '1–3 weeks',
        documents: ['ID if available', 'Any travel documents'],
        whereToGo: 'Your local SPADA platform',
        organization: 'OFII / SPADA',
        officialUrl: 'https://www.ofii.fr',
        instructions: [
          'Find the SPADA covering your region.',
          'Go in person to state you want to seek asylum.',
          'They register your details and book a GUDA appointment.',
        ],
        commonMistakes: ['Going to the wrong office.', 'Not keeping the appointment paper safe.'],
        whatNext: 'You receive an appointment at the single desk (GUDA).',
      },
      {
        id: 'asy-2',
        title: 'Register at the GUDA',
        purpose: 'Official registration of your asylum request and fingerprinting.',
        duration: '1 day',
        documents: ['SPADA appointment', 'Photos'],
        whereToGo: 'Guichet unique (GUDA)',
        organization: 'Préfecture + OFII',
        officialUrl: 'https://www.ofii.fr',
        instructions: [
          'Attend your GUDA appointment on time.',
          'Give fingerprints and personal details.',
          'Receive your asylum-seeker certificate (attestation).',
        ],
        commonMistakes: ['Arriving late or missing the appointment.', 'Incomplete personal information.'],
        whatNext: 'You get the attestation de demande d’asile and OFII reception conditions.',
      },
      {
        id: 'asy-3',
        title: 'Receive your asylum-seeker certificate',
        purpose: 'Proof of your right to remain in France during the procedure.',
        duration: 'Same day',
        documents: ['GUDA registration'],
        whereToGo: 'GUDA',
        organization: 'Préfecture',
        officialUrl: 'https://www.ofpra.gouv.fr',
        instructions: [
          'Keep the attestation safe — it proves your legal stay.',
          'Note its validity and renewal dates.',
        ],
        commonMistakes: ['Letting it expire without renewing.'],
        whatNext: 'You can now prepare and send your OFPRA application.',
      },
      {
        id: 'asy-4',
        title: 'Submit your OFPRA application',
        purpose: 'Your detailed asylum account, due within 21 days of registration.',
        duration: '1–3 weeks',
        documents: ['Attestation de demande d’asile', 'Written account of your story'],
        whereToGo: 'By post to OFPRA',
        organization: 'OFPRA',
        officialUrl: 'https://www.ofpra.gouv.fr',
        instructions: [
          'Write your personal account clearly and honestly.',
          'Complete the OFPRA form you received.',
          'Send it by registered post before the deadline.',
        ],
        commonMistakes: ['Missing the 21-day deadline.', 'Vague or inconsistent account.'],
        whatNext: 'OFPRA reviews your file and calls you to an interview.',
      },
      {
        id: 'asy-5',
        title: 'Attend your OFPRA interview',
        purpose: 'The decisive step where you explain your situation in person.',
        duration: '1–12 months',
        documents: ['Convocation letter', 'Supporting evidence'],
        whereToGo: 'OFPRA (Fontenay-sous-Bois) or by video',
        organization: 'OFPRA',
        officialUrl: 'https://www.ofpra.gouv.fr',
        instructions: [
          'Bring your convocation and any evidence.',
          'Request an interpreter if needed.',
          'Explain your story clearly and consistently.',
        ],
        commonMistakes: ['Not requesting an interpreter.', 'Forgetting key evidence.'],
        whatNext: 'OFPRA sends a written decision; if refused, you can appeal to the CNDA.',
      },
    ],
  },
  {
    id: 'nationality',
    title: 'French nationality',
    subtitle: 'Apply for naturalisation',
    icon: 'flag-outline',
    accent: Colors.red,
    steps: [
      {
        id: 'nat-1',
        title: 'Check you meet the conditions',
        purpose: 'Usually 5 years of residence, stable income and integration are required.',
        duration: '1 hour',
        documents: ['Residence history', 'Income proof'],
        whereToGo: 'Read criteria on service-public.fr',
        organization: 'Ministère de l’Intérieur',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N111',
        instructions: [
          'Read the naturalisation conditions.',
          'Check your years of residence and income stability.',
          'Note any exceptions that apply to you.',
        ],
        commonMistakes: ['Applying before meeting the residence requirement.'],
        whatNext: 'You know whether you’re eligible to apply now or later.',
      },
      {
        id: 'nat-2',
        title: 'Pass a French language test (B1)',
        purpose: 'Proof of at least B1 spoken and written French is required.',
        duration: '1–2 months',
        documents: ['ID', 'Test registration'],
        whereToGo: 'An approved test centre (TCF/DELF)',
        organization: 'Approved language centre',
        officialUrl: 'https://www.france-education-international.fr',
        instructions: [
          'Choose an approved test (TCF Intégration or DELF B1+).',
          'Register and pay for a session.',
          'Take the test and keep your certificate.',
        ],
        commonMistakes: ['Taking a non-approved test.', 'Forgetting the certificate is required in the file.'],
        whatNext: 'Your language certificate goes into your naturalisation file.',
      },
      {
        id: 'nat-3',
        title: 'Build your naturalisation file',
        purpose: 'A thorough, well-organised file is essential to avoid rejection.',
        duration: '2–4 weeks',
        documents: ['Birth certificate (translated)', 'Tax notices', 'Payslips', 'Residence permits', 'Language certificate'],
        whereToGo: 'At home — scan as PDF',
        organization: 'Préfecture',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N111',
        instructions: [
          'Collect civil-status, tax and income documents.',
          'Get official translations where required.',
          'Scan everything clearly and organise by category.',
        ],
        commonMistakes: ['Missing tax notices.', 'Non-official translations.'],
        whatNext: 'With a complete file, you can submit your application.',
      },
      {
        id: 'nat-4',
        title: 'Submit your application',
        purpose: 'Officially lodge your naturalisation request.',
        duration: '1 hour',
        documents: ['Complete file'],
        whereToGo: 'natali (online) or by post',
        organization: 'Préfecture / Ministère',
        officialUrl: 'https://anef.administration-etrangers.interieur.gouv.fr/particuliers/#/',
        instructions: [
          'Submit via the online platform or by registered post.',
          'Keep your submission proof.',
          'Wait for the acknowledgement of receipt.',
        ],
        commonMistakes: ['Submitting an incomplete file.'],
        whatNext: 'You’ll be invited to an integration interview.',
      },
      {
        id: 'nat-5',
        title: 'Attend the integration interview',
        purpose: 'A final assessment of your integration before the decision.',
        duration: '6–18 months',
        documents: ['Convocation', 'Originals of documents'],
        whereToGo: 'Your préfecture',
        organization: 'Préfecture',
        officialUrl: 'https://www.service-public.fr/particuliers/vosdroits/N111',
        instructions: [
          'Bring originals of your documents.',
          'Review basic French history and values.',
          'Answer questions calmly about your life in France.',
        ],
        commonMistakes: ['Forgetting original documents.', 'Not preparing for civic questions.'],
        whatNext: 'You receive a decision; if granted, you’re invited to a citizenship ceremony.',
      },
    ],
  },
  {
    id: 'other',
    title: 'Something else',
    subtitle: 'A general checklist for any procedure',
    icon: 'ellipsis-horizontal-outline',
    accent: Colors.textSecondary,
    steps: [
      {
        id: 'oth-1',
        title: 'Identify the right organization',
        purpose: 'Knowing who handles your request (CAF, CPAM, préfecture…) saves a lot of time.',
        duration: '30 minutes',
        documents: ['Your letters / situation'],
        whereToGo: 'Use the AI tools to find out',
        organization: 'PrefAI',
        officialUrl: 'https://www.service-public.fr',
        instructions: [
          'Describe your situation to the AI assistant.',
          'Identify the responsible organization.',
          'Find their official website.',
        ],
        commonMistakes: ['Contacting the wrong administration.'],
        whatNext: 'You know exactly who to deal with.',
      },
      {
        id: 'oth-2',
        title: 'Gather common documents',
        purpose: 'Most procedures need the same core set of papers.',
        duration: '1–3 days',
        documents: ['Passport / ID', 'Proof of address', 'RIB', 'Residence permit'],
        whereToGo: 'At home',
        organization: '—',
        officialUrl: 'https://www.service-public.fr',
        instructions: [
          'Collect your ID, proof of address and RIB.',
          'Scan each as a clear PDF.',
          'Keep them in one folder.',
        ],
        commonMistakes: ['Out-of-date proof of address.'],
        whatNext: 'You’re ready for almost any administrative request.',
      },
      {
        id: 'oth-3',
        title: 'Prepare your request',
        purpose: 'Translate and write what you need to send.',
        duration: '1 day',
        documents: ['Your situation described'],
        whereToGo: 'AI Reply & Translate tools',
        organization: 'PrefAI',
        officialUrl: 'https://www.service-public.fr',
        instructions: [
          'Use AI Reply to draft your letter in French.',
          'Use Translate to understand any reply.',
          'Review before sending.',
        ],
        commonMistakes: ['Sending without checking the French.'],
        whatNext: 'Your request is ready to submit.',
      },
      {
        id: 'oth-4',
        title: 'Submit and track deadlines',
        purpose: 'Send your request and never miss a response date.',
        duration: 'Varies',
        documents: ['Completed request'],
        whereToGo: 'Relevant portal or office',
        organization: '—',
        officialUrl: 'https://www.service-public.fr',
        instructions: [
          'Submit via the correct channel.',
          'Add any deadline to the Deadline Tracker.',
          'Follow up if you hear nothing.',
        ],
        commonMistakes: ['Not tracking the response deadline.'],
        whatNext: 'You stay on top of your procedure from start to finish.',
      },
    ],
  },
];

export const getJourney = (id: JourneyId): Journey =>
  JOURNEYS.find((j) => j.id === id) ?? JOURNEYS[JOURNEYS.length - 1];

export const getJourneyStep = (id: JourneyId, stepId: string): JourneyStep | undefined =>
  getJourney(id).steps.find((s) => s.id === stepId);
