/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/sync-mes-aides-benefits.cjs — do not edit by hand.
 * Source: Mes Aides / 1jeune1solution /api/benefits
 * Licence: Licence Ouverte (Etalab)
 * Synced: 2026-09-07T10:05:00.877Z
 * Count: 78
 */

export const MES_AIDES_SYNCED_AT = "2026-09-07T10:05:00.877Z";

export const MES_AIDES_BENEFITS = [
  {
    "id": "caf-haute-saone-aide-autonomie",
    "slug": "caf-haute-saone-aide-autonomie",
    "label": "aide à l'autonomie des jeunes",
    "description": "Cette aide vous permet de vous financer vos frais de scolarité, de formation, de garde d’enfant, etc. dans le cadre d'une insertion professionnelle.",
    "institution": "CAF de Haute-Saône",
    "link": "https://caf.fr/allocataires/caf-de-la-haute-saone/offre-de-service/vie-professionnelle/autonomie-des-jeunes",
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "70"
        ]
      }
    ]
  },
  {
    "id": "caf-meurthe-et-moselle-aide-bafa-approfondissement",
    "slug": "caf-meurthe-et-moselle-aide-bafa-approfondissement",
    "label": "aide au BAFA",
    "description": "La CAF de Meurthe-et-Moselle soutient les jeunes qui passent leur BAFA en leur versant une aide complémentaire à celle apportée par la CNAF. L'aide est versée à l'issue de la session de perfectionnement et son montant peut varier en fonction du parcours et des besoins du jeune qu",
    "institution": "CAF de Meurthe-et-Moselle",
    "link": "https://www.caf.fr/allocataires/caf-de-meurthe-et-moselle/offre-de-service/vie-personnelle/les-aides-aux-formations-bafa-et-bafd",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 17
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "54"
        ]
      }
    ]
  },
  {
    "id": "caf-nord-aide-bafa-approfondissement",
    "slug": "caf-nord-aide-bafa-approfondissement",
    "label": "aide au BAFA",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la Caf du Nord en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Nord",
    "link": "https://caf.fr/allocataires/caf-du-nord/offre-de-service/vie-professionnelle/l-aide-au-brevet-d-aptitude-aux-fonctions-d-animateur-bafa",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "59"
        ]
      }
    ]
  },
  {
    "id": "departement_mayenne-aide-au-bafa-du-departement-de-la-mayenne",
    "slug": "departement_mayenne-aide-au-bafa-du-departement-de-la-mayenne",
    "label": "Aide au BAFA du département de la Mayenne",
    "description": "Le Département de la Mayenne accorde une aide unique de 300 euros à toute personne âgée de 16 à 26 ans s’engageant à suivre l’intégralité de la formation BAFA. La demande d'aide doit être effectuée à la fin de la session de formation générale et au plus tard dans le mois suivant ",
    "institution": "Département de la Mayenne",
    "link": "https://www.lamayenne.fr/service/aide-pour-passer-le-bafa",
    "amount": 300,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "53"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 26
      }
    ]
  },
  {
    "id": "caf-haute-saone-aide-bafa",
    "slug": "caf-haute-saone-aide-bafa",
    "label": "aide au BAFA et BAFD",
    "description": "Votre CAF départementale vous aide à financer votre BAFA (de la session générale à la session d'approfondissement) et votre BAFD, en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Haute-Saône",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-saone/offre-de-service/vie-professionnelle/bafa-bafd-dispositif-local",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "70"
        ]
      }
    ]
  },
  {
    "id": "caf-seine-st-denis-aide-bafa-approfondissement",
    "slug": "caf-seine-st-denis-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session d'approfondissement",
    "description": "L’aide à la formation du BAFA est une aide locale de 200 € mise à disposition par la CAF de Seine-Saint-Denis pour vous aider à financer votre session d’approfondissement ou de qualification, en complément de l'aide nationale apportée par la CAF. Cette aide est majorée de 100 € s",
    "institution": "CAF de Seine-Saint-Denis",
    "link": "https://www.caf.fr/allocataires/caf-de-la-seine-saint-denis/offre-de-service/vie-professionnelle/l-aide-la-formation-bafa-session-d-approfondissement",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 17
      },
      {
        "type": "departements",
        "values": [
          "93"
        ]
      }
    ]
  },
  {
    "id": "aide-au-bafa-pour-une-session-dapprofondissement-ou-de-qualification-caf-de-la-haute-savoie",
    "slug": "aide-au-bafa-pour-une-session-dapprofondissement-ou-de-qualification-caf-de-la-haute-savoie",
    "label": "aide au BAFA pour une session d'approfondissement ou de qualification",
    "description": "L'aide au BAFA pour une session de formation générale est une aide locale mise à disposition par la CAF de la Haute-Savoie pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.<br><br>Pour bénéficier de cette aide, contactez directement l",
    "institution": "CAF de la Haute-Savoie",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-savoie/offre-de-service/vie-professionnelle/solidarite-et-insertion",
    "amount": 109,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "74"
        ]
      }
    ]
  },
  {
    "id": "caf-correze-aide-bafa-approfondissement",
    "slug": "caf-correze-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session d'approfondissement ou de qualification",
    "description": "Cette aide est mise à disposition par la CAF de la Corrèze pour aider les jeunes à financer la troisième et dernière partie de leur formation au BAFA, en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Corrèze",
    "link": "https://www.caf.fr/allocataires/caf-de-la-correze/offre-de-service/thematique-libre/le-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "19"
        ]
      }
    ]
  },
  {
    "id": "caf-ain-aide-bafa-session-approfondissement-qualification",
    "slug": "caf-ain-aide-bafa-session-approfondissement-qualification",
    "label": "aide au BAFA pour une session d’approfondissement ou de qualification",
    "description": "Vous souhaitez terminer votre formation BAFA par la session d'approfondissement ou par la session de qualification centrée sur l’accueil du jeune enfant ? Vous pouvez percevoir à une aide de la part de la CAF de l'Ain. Cette aide vous est versée directement.",
    "institution": "CAF de l'Ain",
    "link": "https://www.caf.fr/allocataires/caf-de-l-ain/offre-de-service/vie-professionnelle/vous-accompagner-pour-passer-le-bafa",
    "amount": 250,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "01"
        ]
      }
    ]
  },
  {
    "id": "caf-drome-aide-bafa-session-approfondissement-qualification",
    "slug": "caf-drome-aide-bafa-session-approfondissement-qualification",
    "label": "aide au BAFA pour une session d’approfondissement ou de qualification",
    "description": "La CAF de la Drôme vous aide à financer votre session d'approfondissement ou de qualification (troisième et dernière étape du diplôme du BAFA) en complément de l'aide nationale apportée par la CNAF. La CAF de la Drôme verse cette aide à l'organisme de formation qui la déduit du m",
    "institution": "CAF de la Drôme",
    "link": "https://www.caf.fr/allocataires/caf-de-la-drome/offre-de-service/vie-professionnelle/aides-au-bafa",
    "amount": 225,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 17
      },
      {
        "type": "departements",
        "values": [
          "26"
        ]
      }
    ]
  },
  {
    "id": "caf-haute-loire-aide-bafa-approfondissement",
    "slug": "caf-haute-loire-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session d’approfondissement ou de qualification",
    "description": "L'aide au BAFA pour une session d'approfondissement ou de qualification est une aide locale mise à disposition par la CAF de la Haute-Loire pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Haute-Loire",
    "link": "https://caf.fr/allocataires/caf-de-haute-loire/offre-de-service/vie-personnelle/les-aides-la-formation-bafa-et-bafd",
    "amount": 165,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "43"
        ]
      }
    ]
  },
  {
    "id": "caf-loire-aide-bafa-approfondissement",
    "slug": "caf-loire-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session d’approfondissement ou de qualification",
    "description": "L'aide au BAFA pour une session d'approfondissement ou de qualification est une aide locale mise à disposition par la CAF de la Loire pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Loire",
    "link": "https://caf.fr/allocataires/caf-de-la-loire/offre-de-service/vie-personnelle/l-aide-au-bafa",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "42"
        ]
      }
    ]
  },
  {
    "id": "caf-alpes-maritimes-aide-bafa-approfondissement",
    "slug": "caf-alpes-maritimes-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Alpes-Maritimes pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Alpes-Maritimes",
    "link": "https://www.caf.fr/allocataires/caf-des-alpes-maritimes/offre-de-service/vie-personnelle/votre-enfant-16-ans-et-et-vous-souhaitez-le-soutenir-dans-ses-projets",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "06"
        ]
      }
    ]
  },
  {
    "id": "caf-ardennes-aide-bafa-approfondissement",
    "slug": "caf-ardennes-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Ardennes pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Ardennes",
    "link": "https://caf.fr/allocataires/caf-des-ardennes/offre-de-service/vie-personnelle/le-bafa",
    "amount": 330,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "08"
        ]
      }
    ]
  },
  {
    "id": "caf-aveyron-aide-bafa-approfondissement",
    "slug": "caf-aveyron-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de l'Aveyron pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de l'Aveyron",
    "link": "https://www.caf.fr/allocataires/caf-de-l-aveyron/offre-de-service/vie-professionnelle/bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "12"
        ]
      }
    ]
  },
  {
    "id": "caf-bas-rhin-aide-bafa-approfondissement",
    "slug": "caf-bas-rhin-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Bas-Rhin pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Bas-Rhin",
    "link": "https://www.caf.fr/allocataires/caf-du-bas-rhin/offre-de-service/vie-professionnelle/l-aide-au-bafa-brevet-d-aptitude-aux-fonctions-d-animateur",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "67"
        ]
      }
    ]
  },
  {
    "id": "caf-corse-du-sud-aide-bafa-approfondissement",
    "slug": "caf-corse-du-sud-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Corse du Sud pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Corse-du-Sud",
    "link": "https://caf.fr/allocataires/caf-de-corse-du-sud/offre-de-service/vie-personnelle/le-brevet-d-aptitude-aux",
    "amount": 207,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "2A"
        ]
      }
    ]
  },
  {
    "id": "caf-cotes-armor-aide-bafa-approfondissement",
    "slug": "caf-cotes-armor-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Côtes d'Armor pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Côtes-d'Armor",
    "link": "https://caf.fr/allocataires/caf-des-cotes-d-armor/offre-de-service/vie-professionnelle/bafa-et-bafd",
    "amount": 450,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "22"
        ]
      }
    ]
  },
  {
    "id": "caf-doubs-aide-bafa-approfondissement",
    "slug": "caf-doubs-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Doubs pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Doubs",
    "link": "https://caf.fr/allocataires/caf-du-doubs/offre-de-service/vie-professionnelle/le-bafa-et-le-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "25"
        ]
      }
    ]
  },
  {
    "id": "caf-indre-et-loire-aide-bafa-approfondissement",
    "slug": "caf-indre-et-loire-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "Le brevet d’aptitude aux fonctions d’animateur (BAFA) est un diplôme qui permet d’encadrer des enfants et des adolescents en accueil collectif de mineurs. La CAF de l'Indre-et-Loire, vous aide à financer la troisième étape de votre diplôme, une session d’approfondissement (de 6 j",
    "institution": "CAF d'Indre-et-Loire",
    "link": "https://www.caf.fr/allocataires/caf-de-touraine/offre-de-service/vie-personnelle/j-ai-un-enfant-de-plus-de-16-ans-qui-souhaite-une-formation-bafa",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "37"
        ]
      }
    ]
  },
  {
    "id": "caf-jura-aide-bafa-approfondissement",
    "slug": "caf-jura-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Jura pour vous aider à financer en grande partie votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Jura",
    "link": "https://caf.fr/allocataires/caf-du-jura/offre-de-service/vie-personnelle/l-aide-la-formation-bafabafad",
    "amount": 90,
    "unit": "%",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "39"
        ]
      }
    ]
  },
  {
    "id": "caf-loire-atlantique-aide-bafa-approfondissement",
    "slug": "caf-loire-atlantique-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Loire-Atlantique pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Loire-Atlantique",
    "link": "https://www.caf.fr/allocataires/caf-de-loire-atlantique/offre-de-service/vie-personnelle/vacances-et-loisirs/comment-financer-le-bafa",
    "amount": 208,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "44"
        ]
      }
    ]
  },
  {
    "id": "caf-loiret-aide-bafa-approfondissement",
    "slug": "caf-loiret-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "La CAF du Loiret vous aide à financer votre session de formation d'approfondissement (troisième et dernière étape du diplôme du BAFA) en complément de l'aide nationale apportée par la CNAF. Le dossier de demande doit être complété, signé et adressé à la CAF du Loiret à l’issue de",
    "institution": "CAF du Loiret",
    "link": "https://caf.fr/allocataires/caf-du-loiret/offre-de-service/vie-professionnelle/vous-souhaitez-devenir-animateur-grace-au-bafa-bafd",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 26
      },
      {
        "type": "departements",
        "values": [
          "45"
        ]
      }
    ]
  },
  {
    "id": "caf-mayenne-aide-bafa-approfondissement",
    "slug": "caf-mayenne-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de la Mayenne pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Mayenne",
    "link": "https://wwwd.caf.fr/wps/portal/caffr/aidesetservices/lesservicesenligne/faireunedemandedeprestation#DBAFA",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "53"
        ]
      }
    ]
  },
  {
    "id": "caf-morbihan-aide-bafa-approfondissement",
    "slug": "caf-morbihan-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Morbihan pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Morbihan",
    "link": "https://caf.fr/allocataires/caf-du-morbihan/offre-de-service/vie-professionnelle/bourses-bafa-et-bafd",
    "amount": 286,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "56"
        ]
      }
    ]
  },
  {
    "id": "caf-reunion-aide-bafa-approfondissement",
    "slug": "caf-reunion-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L’aide de la CAF de La Réunion pour la session d’approfondissement du BAFA permet aux jeunes réunionnais de bénéficier d’un soutien financier pour terminer leur formation. Cette aide, attribuée sans condition de ressources, peut atteindre 400 € pour une session en internat et 300",
    "institution": "CAF de La Réunion",
    "link": "https://www.caf.fr/allocataires/caf-de-la-reunion/offre-de-service/vie-professionnelle/le-bafa-ou-le-bafd-vous-tente-votre-caf-peut-vous-aider",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "974"
        ]
      }
    ]
  },
  {
    "id": "caf-territoire-de-belfort-aide-bafa-approfondissement",
    "slug": "caf-territoire-de-belfort-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Territoire de Belfort pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Territoire de Belfort",
    "link": "https://www.caf.fr/allocataires/caf-du-territoire-de-belfort/offre-de-service/vie-professionnelle/la-bourse-de-stage-d-animateur-ou-de-directeur-de-centres-de-vacances-et-de-loisirs",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "90"
        ]
      }
    ]
  },
  {
    "id": "caf-vaucluse-aide-bafa-approfondissement",
    "slug": "caf-vaucluse-aide-bafa-approfondissement",
    "label": "aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Vaucluse pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Vaucluse",
    "link": "https://caf.fr/allocataires/caf-de-vaucluse/offre-de-service/vie-professionnelle/le-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "84"
        ]
      }
    ]
  },
  {
    "id": "caf-gironde-aide-au-bafa-pour-une-session-de-formation-dapprofondissement",
    "slug": "caf-gironde-aide-au-bafa-pour-une-session-de-formation-dapprofondissement",
    "label": "Aide au BAFA pour une session de formation d'approfondissement",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Gironde pour vous aider à financer votre session d’approfondissement en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Gironde",
    "link": "https://caf.fr/allocataires/caf-de-la-gironde/offre-de-service/vie-professionnelle/le-bafa",
    "amount": 300,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "33"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "33"
        ]
      }
    ]
  },
  {
    "id": "caf-ardeche-aide-bafa",
    "slug": "caf-ardeche-aide-bafa",
    "label": "aide au BAFA pour une session de formation d'approfondissement ou de qualification",
    "description": "La CAF de l'Ardèche peut financer une partie de la session d'approfondissement au BAFA. Cette aide n'est pas cumulable avec l'aide nationale apportée par la CAF.",
    "institution": "CAF de l'Ardèche",
    "link": "https://www.caf.fr/allocataires/caf-de-l-ardeche/offre-de-service/vie-personnelle/le-bafa",
    "amount": 315,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "07"
        ]
      }
    ]
  },
  {
    "id": "caf_oise-aide-au-bafa-pour-une-session-de-formation-dapprofondissement-ou-de-qualification",
    "slug": "caf_oise-aide-au-bafa-pour-une-session-de-formation-dapprofondissement-ou-de-qualification",
    "label": "Aide au BAFA pour une session de formation d'approfondissement ou de qualification",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la Caf de l'Oise pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de l'Oise",
    "link": "https://caf.fr/allocataires/caf-de-l-oise/offre-de-service/vie-professionnelle/je-souhaite-passer-mon-bafa-et-obtenir-une-aide-financiere",
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "60"
        ]
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 16
      }
    ]
  },
  {
    "id": "aide-au-bafa-pour-une-session-de-formation-générale-caf-de-la-haute-savoie",
    "slug": "aide-au-bafa-pour-une-session-de-formation-générale-caf-de-la-haute-savoie",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide au BAFA pour une session de formation générale est une aide locale mise à disposition par la CAF de la Haute-Savoie pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF. <br> <br> Pour bénéficier de cette aide, contactez directemen",
    "institution": "CAF de la Haute-Savoie",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-savoie/offre-de-service/vie-professionnelle/solidarite-et-insertion",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "74"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      }
    ]
  },
  {
    "id": "caf-ardennes-aide-bafa-generale",
    "slug": "caf-ardennes-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Ardennes pour vous aider à financer votre session en complément de l'aide nationale l'aide nationale apportée par la CAF.",
    "institution": "CAF des Ardennes",
    "link": "https://caf.fr/allocataires/caf-des-ardennes/offre-de-service/vie-personnelle/le-bafa",
    "amount": 280,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "08"
        ]
      }
    ]
  },
  {
    "id": "caf-bas-rhin-aide-bafa-generale",
    "slug": "caf-bas-rhin-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Bas-Rhin pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Bas-Rhin",
    "link": "https://www.caf.fr/allocataires/caf-du-bas-rhin/offre-de-service/vie-professionnelle/l-aide-au-bafa-brevet-d-aptitude-aux-fonctions-d-animateur",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "67"
        ]
      }
    ]
  },
  {
    "id": "caf-deux-sevres-aide-bafa-generale",
    "slug": "caf-deux-sevres-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide au BAFA pour une session de formation générale est une aide locale mise à disposition par la CAF des Deux-Sèvres pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Deux-Sèvres",
    "link": "https://www.caf.fr/allocataires/caf-des-deux-sevres/offre-de-service/vie-personnelle/jeunesse/je-recherche-une-aide-pour-passer-mon-bafa",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "79"
        ]
      }
    ]
  },
  {
    "id": "caf-doubs-aide-bafa-generale",
    "slug": "caf-doubs-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Doubs pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Doubs",
    "link": "https://caf.fr/allocataires/caf-du-doubs/offre-de-service/vie-professionnelle/le-bafa-et-le-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "25"
        ]
      }
    ]
  },
  {
    "id": "caf-haute-marne-aide-bafa-generale",
    "slug": "caf-haute-marne-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Haute-Marne pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Haute-Marne",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-marne/offre-de-service/vie-personnelle/enfance-et-jeunesse/bafa-et-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "52"
        ]
      }
    ]
  },
  {
    "id": "caf-hautes-alpes-aide-bafa-generale",
    "slug": "caf-hautes-alpes-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Hautes-Alpes pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Hautes-Alpes",
    "link": "https://caf.fr/allocataires/caf-des-hautes-alpes/offre-de-service/vie-professionnelle/aide-au-brevet-d-aptitude-aux-fonctions-d-animateur-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "05"
        ]
      }
    ]
  },
  {
    "id": "caf-indre-et-loire-aide-bafa-generale",
    "slug": "caf-indre-et-loire-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "Le brevet d’aptitude aux fonctions d’animateur (BAFA) est un diplôme qui permet d’encadrer des enfants et des adolescents en accueil collectif de mineurs. La CAF de l'Indre-et-Loire, vous aide à financer la première étape de ce diplôme, appelée session de formation générale (une ",
    "institution": "CAF d'Indre-et-Loire",
    "link": "https://www.caf.fr/allocataires/caf-de-touraine/offre-de-service/vie-personnelle/j-ai-un-enfant-de-plus-de-16-ans-qui-souhaite-une-formation-bafa",
    "amount": 250,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "37"
        ]
      }
    ]
  },
  {
    "id": "caf-jura-aide-bafa-generale",
    "slug": "caf-jura-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Jura pour vous aider à financer en grande partie votre session en complément de l'aide nationale apportée par la caf.",
    "institution": "CAF du Jura",
    "link": "https://www.caf.fr/allocataires/caf-du-jura/offre-de-service/vie-personnelle/l-aide-la-formation-bafabafad",
    "amount": 90,
    "unit": "%",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "39"
        ]
      }
    ]
  },
  {
    "id": "caf-loire-aide-bafa-generale",
    "slug": "caf-loire-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide au BAFA pour une session de formation générale est une aide locale mise à disposition par la CAF de la Loire pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Loire",
    "link": "https://caf.fr/allocataires/caf-de-la-loire/offre-de-service/vie-personnelle/l-aide-au-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "42"
        ]
      }
    ]
  },
  {
    "id": "caf-loiret-aide-bafa-generale",
    "slug": "caf-loiret-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "La CAF du Loiret vous aide à financer votre session de formation générale (première étape du diplôme du BAFA) en complément de l'aide nationale apportée par la CNAF. Le dossier de demande doit être complété, signé et adressé à la CAF du Loiret à l’issue de la formation générale, ",
    "institution": "CAF du Loiret",
    "link": "https://caf.fr/allocataires/caf-du-loiret/offre-de-service/vie-professionnelle/vous-souhaitez-devenir-animateur-grace-au-bafa-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 26
      },
      {
        "type": "departements",
        "values": [
          "45"
        ]
      }
    ]
  },
  {
    "id": "caf-mayenne-aide-bafa-generale",
    "slug": "caf-mayenne-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de la Mayenne pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Mayenne",
    "link": "https://www.caf.fr/allocataires/caf-de-la-mayenne/offre-de-service/vie-personnelle/jeunes-et-autonomie/bafabafd-votre-caf-vous-aide",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "53"
        ]
      }
    ]
  },
  {
    "id": "caf-meuse-aide-bafa-generale",
    "slug": "caf-meuse-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de la Meuse pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Meuse",
    "link": "https://caf.fr/allocataires/caf-de-la-meuse/offre-de-service/vie-professionnelle/l-aide-la-formation-bafa-bafd",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "55"
        ]
      }
    ]
  },
  {
    "id": "caf-puy-de-dome-aide-bafa-generale",
    "slug": "caf-puy-de-dome-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide au BAFA pour une session de formation générale est une aide locale mise à disposition par la CAF du Puy-de-Dôme pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Puy-de-Dôme",
    "link": "https://caf.fr/allocataires/caf-du-puy-de-dome/offre-de-service/vie-personnelle/aide-au-bafa#:~:text=Le%20dispositif%20local",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "63"
        ]
      }
    ]
  },
  {
    "id": "caf-reunion-aide-bafa-generale",
    "slug": "caf-reunion-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "La CAF de La Réunion prend en charge 100 € pour la session de formation générale du BAFA, sans condition de ressources ni de revenus. Pour en bénéficier, il suffit d’atteindre l’âge requis (16 ans au début de la session) et d’être inscrit dans une formation BAFA agréée. La demand",
    "institution": "CAF de La Réunion",
    "link": "https://www.caf.fr/allocataires/caf-de-la-reunion/offre-de-service/vie-professionnelle/le-bafa-ou-le-bafd-vous-tente-votre-caf-peut-vous-aider",
    "amount": 100,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "974"
        ]
      }
    ]
  },
  {
    "id": "caf-saone-et-loire-aide-bafa-generale",
    "slug": "caf-saone-et-loire-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Saône-et-Loire pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Saône-et-Loire",
    "link": "https://caf.fr/allocataires/caf-de-saone-et-loire/offre-de-service/vie-professionnelle/les-aides-au-brevet-d-aptitude-aux-fonctions-d-animateur-bafa",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "71"
        ]
      }
    ]
  },
  {
    "id": "caf-seine-et-marne-aide-bafa-generale",
    "slug": "caf-seine-et-marne-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Seine-et-Marne pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF Seine et Marne",
    "link": "https://www.caf.fr/allocataires/caf-de-seine-et-marne/offre-de-service/vie-professionnelle/les-aides-la-formation-bafa",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "77"
        ]
      }
    ]
  },
  {
    "id": "caf-somme-aide-bafa-generale",
    "slug": "caf-somme-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de la Somme pour vous aider à financer votre session de formation générale en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Somme",
    "link": "https://www.caf.fr/allocataires/caf-de-la-somme/offre-de-service/vie-professionnelle/l-aide-au-bafa#:~:text=Votre%20Caf%20peut%20vous%20aider,tr%C3%A8s%20recherch%C3%A9e%20dans%20la%20Somme.&text=La%20Caf%20accorde%20%C3%A0%20tous,d%C3%A9duite%20de%20la%20facture%20totale.",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "80"
        ]
      }
    ]
  },
  {
    "id": "caf-territoire-de-belfort-aide-bafa-generale",
    "slug": "caf-territoire-de-belfort-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Territoire de Belfort pour vous aider à financer votre session en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Territoire de Belfort",
    "link": "https://www.caf.fr/allocataires/caf-du-territoire-de-belfort/offre-de-service/vie-professionnelle/la-bourse-de-stage-d-animateur-ou-de-directeur-de-centres-de-vacances-et-de-loisirs",
    "amount": 150,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      },
      {
        "type": "departements",
        "values": [
          "90"
        ]
      }
    ]
  },
  {
    "id": "caf-vaucluse-aide-bafa-generale",
    "slug": "caf-vaucluse-aide-bafa-generale",
    "label": "aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF du Vaucluse pour vous aider à financer votre session générale en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Vaucluse",
    "link": "https://caf.fr/allocataires/caf-de-vaucluse/offre-de-service/vie-professionnelle/le-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "84"
        ]
      }
    ]
  },
  {
    "id": "caf-alpes-maritimes-aide-bafa-generale",
    "slug": "caf-alpes-maritimes-aide-bafa-generale",
    "label": "Aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF des Alpes-Maritimes pour vous aider à financer votre session générale, en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Alpes-Maritimes",
    "link": "https://www.caf.fr/allocataires/caf-des-alpes-maritimes/offre-de-service/vie-personnelle/votre-enfant-16-ans-et-et-vous-souhaitez-le-soutenir-dans-ses-projets",
    "amount": 350,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "06"
        ]
      }
    ]
  },
  {
    "id": "caf_maine_et_loire-aide-au-bafa-pour-une-session-de-formation-générale",
    "slug": "caf_maine_et_loire-aide-au-bafa-pour-une-session-de-formation-générale",
    "label": "Aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de Maine-et-Loire pour vous aider à financer votre session de formation en complément de l'aide nationale apportée par la CAF",
    "institution": "CAF de Maine-et-Loire",
    "link": "https://caf.fr/allocataires/caf-de-maine-et-loire/offre-de-service/vie-personnelle/je-souhaite-beneficier-de-l-aide-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "49"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      }
    ]
  },
  {
    "id": "caf_oise-aide-au-bafa-pour-une-session-de-formation-générale",
    "slug": "caf_oise-aide-au-bafa-pour-une-session-de-formation-générale",
    "label": "Aide au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de l'Oise pour vous aider à financer votre session d’approfondissement ou de qualification en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de l'Oise",
    "link": "https://caf.fr/allocataires/caf-de-l-oise/offre-de-service/vie-professionnelle/je-souhaite-passer-mon-bafa-et-obtenir-une-aide-financiere",
    "amount": 350,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "60"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      }
    ]
  },
  {
    "id": "caf-guyane-aide-bafa",
    "slug": "caf-guyane-aide-bafa",
    "label": "aide au BAFA pour une session de formation générale et d'approfondissement",
    "description": "L’aide à la formation du BAFA est une aide locale de 200 € par session théorique (formation générale et formation d'approfondissement), mise à disposition par la CAF de la Guyane en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de Guyane",
    "link": "https://www.caf.fr/allocataires/caf-de-la-guyane/offre-de-service/vie-personnelle/aide-au-brevet-d-aptitude-aux-fonctions-d-animation-bafa",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "973"
        ]
      }
    ]
  },
  {
    "id": "departement_mayenne-aide-au-bafd",
    "slug": "departement_mayenne-aide-au-bafd",
    "label": "Aide au BAFD du département de la Mayenne",
    "description": "Le Département de la Mayenne prend en charge une partie du coût de la formation au brevet d’aptitude aux fonctions de directeur (BAFD), pour toute personne s'engageant à suivre la formation, sans conditions de ressources.",
    "institution": "Département de la Mayenne",
    "link": "https://www.lamayenne.fr/service/aide-pour-passer-le-bafd",
    "amount": 450,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "53"
        ]
      }
    ]
  },
  {
    "id": "caf-haute-marne-aide-bafd",
    "slug": "caf-haute-marne-aide-bafd",
    "label": "aide au Brevet d'Aptitude aux Fonctions de Directeur (BAFD)",
    "description": "L'aide proposée par la CAF de la Haute-Marne peut vous aider à financer votre session de formation au BAFD.",
    "institution": "CAF de la Haute-Marne",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-marne/offre-de-service/vie-personnelle/enfance-et-jeunesse/bafa-et-bafd",
    "amount": 400,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "departements",
        "values": [
          "52"
        ]
      }
    ]
  },
  {
    "id": "caf_dordogne-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "slug": "caf_dordogne-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "label": "aide au Brevet d'Aptitude aux Fonctions de Directeur (BAFD)",
    "description": "L'aide proposée par la CAF de Dordogne peut vous aider à financer votre session de formation au BAFD.",
    "institution": "CAF de Dordogne",
    "link": "https://caf.fr/allocataires/caf-de-la-dordogne/offre-de-service/vie-professionnelle/je-souhaite-passer-mon-bafabafd",
    "amount": 250,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "departements",
        "values": [
          "24"
        ]
      }
    ]
  },
  {
    "id": "caf_doubs-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "slug": "caf_doubs-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "label": "aide au Brevet d'Aptitude aux Fonctions de Directeur (BAFD)",
    "description": "L'aide proposée par la CAF du Doubs peut vous aider à financer votre session de formation au BAFD.",
    "institution": "CAF du Doubs",
    "link": "https://caf.fr/allocataires/caf-du-doubs/offre-de-service/vie-professionnelle/le-bafa-et-le-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "departements",
        "values": [
          "25"
        ]
      }
    ]
  },
  {
    "id": "caf_cotes_armor-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "slug": "caf_cotes_armor-aide-au-brevet-daptitude-aux-fonctions-de-directeur-bafd",
    "label": "Aide au Brevet d'Aptitude aux Fonctions de Directeur (BAFD)",
    "description": "L'aide proposée par la CAF des Côtes-d'Armor peut vous aider à financer votre session de formation au BAFD. Le montant total de la participation est versé à l'issue du dernier stage d'approfondissement ou de qualification.",
    "institution": "CAF des Côtes-d'Armor",
    "link": "https://caf.fr/allocataires/caf-des-cotes-d-armor/offre-de-service/vie-professionnelle/bafa-et-bafd",
    "amount": 450,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "departements",
        "values": [
          "22"
        ]
      }
    ]
  },
  {
    "id": "caf_alpes_maritimes-une-aide-au-départ-en-vacances-pour-les-jeunes-le-dispositif-sac-ados",
    "slug": "caf_alpes_maritimes-une-aide-au-départ-en-vacances-pour-les-jeunes-le-dispositif-sac-ados",
    "label": "aide au départ en vacances pour les jeunes : le dispositif Sac Ados",
    "description": "Créé par l’association « Vacances Ouvertes », c'est une aide aux projets de départs en vacances autonomes. Il s'agit de 150 € en chèques vacances pour les départs en France et 250 € en carte prépayée pour les départs vers l'Europe (uniquement pour les majeurs).",
    "institution": "CAF des Alpes-Maritimes",
    "link": "https://www.caf.fr/allocataires/caf-des-alpes-maritimes/offre-de-service/vie-personnelle/vous-avez-besoin-d-une-aide-pour-partir-en-vacances/vous-avez-entre-16-et-25-ans-partez-en-vacances-avec-l-operation-sac-ados",
    "amount": 250,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "06"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  },
  {
    "id": "departement_oise-aide-au-financement-du-permis-de-conduire-permis-citoyen",
    "slug": "departement_oise-aide-au-financement-du-permis-de-conduire-permis-citoyen",
    "label": "Aide au financement du permis de conduire : Permis Citoyen",
    "description": "Ce dispositif permet aux Oisiens de moins de 20 ans de financer leur permis de conduire en contrepartie d’une mission bénévole de 70 heures dans une collectivité ou une association de l’Oise.",
    "institution": "Département de l'Oise",
    "link": "https://www.oise.fr/les-pass-citoyens-du-conseil-departemental-de-loise/le-passpermis-citoyen",
    "amount": 600,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "60"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 19
      }
    ]
  },
  {
    "id": "departement_landes-aide-au-financement-du-permis-de-conduire-permis-citoyen",
    "slug": "departement_landes-aide-au-financement-du-permis-de-conduire-permis-citoyen",
    "label": "Aide au financement du permis de conduire au titre d'un parcours d'engagement",
    "description": "Ce dispositif permet aux jeunes Landais de financer leur permis de conduire en contrepartie d’un parcours d'engagement (service civique, engagement au sein du Corps Européen de Solidarité, mandat de conseiller municipal/intercommunal des jeunes, mandat au sein d’une Association T",
    "institution": "Département Landes",
    "link": "https://www.landes.fr/pack-jeunes-mobilite",
    "amount": 450,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "40"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 15
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 30
      }
    ]
  },
  {
    "id": "caf_haute_garonne-aide-complémentaire-au-bafa-handicap",
    "slug": "caf_haute_garonne-aide-complémentaire-au-bafa-handicap",
    "label": "Aide complémentaire au BAFA Handicap",
    "description": "La Caf de la Haute-Garonne propose une aide complémentaire BAFA Handicap si vous choisissez de suivre un stage d'approfondissement \"Accueil d'enfants en situation de handicap dans les centres de loisirs\", dans un des <a target=\"_blank\" title=\"Organismes conventionnés - Nouvelle f",
    "institution": "CAF de Haute-Garonne",
    "link": "https://www.caf.fr/allocataires/caf-de-la-haute-garonne/offre-de-service/vie-professionnelle/je-souhaite-obtenir-le-bafa",
    "amount": 230,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "31"
        ]
      }
    ]
  },
  {
    "id": "caf-nord-bafd",
    "slug": "caf-nord-bafd",
    "label": "aide complémentaire au Brevet d'aptitude aux fonctions de directeur (BAFD)",
    "description": "L'aide complémentaire au BAFD est une aide locale mise à disposition par la Caf du Nord pour vous aider à financer votre formation.",
    "institution": "CAF du Nord",
    "link": "https://caf.fr/allocataires/caf-du-nord/offre-de-service/vie-professionnelle/l-aide-complementaire-au-brevet-d-aptitude-aux-fonctions-de-directeur-bafd",
    "amount": 250,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "59"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      }
    ]
  },
  {
    "id": "departement_charente_maritime-aide-departementale-au-permis-de-conduire",
    "slug": "departement_charente_maritime-aide-departementale-au-permis-de-conduire",
    "label": "aide départementale au permis de conduire",
    "description": "Le Département aide les jeunes éligibles aux critères du Fonds d'aide aux jeunes à financer leur permis de conduire. Pour effectuer une demande, vous devez être accompagné par un référent : Mission Locale, Comité local pour le logement autonome des jeunes, Foyer jeunes travailleu",
    "institution": "Département Charente-Maritime",
    "link": "https://la.charente-maritime.fr/fiches-aides/aide-au-permis-conduire",
    "amount": 1500,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "17"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  },
  {
    "id": "departement-gironde-aide-departementale-au-permis-de-conduire",
    "slug": "departement-gironde-aide-departementale-au-permis-de-conduire",
    "label": "Aide départementale au Permis de conduire",
    "description": "Le Département facilite l’accès au permis de conduire pour des jeunes en difficultés sociale et financière, domiciliés sur les territoires ruraux où l’offre de transport collectif est peu développée. Cette aide est versée en contrepartie d'un engagement bénévole au sein d'une ass",
    "institution": "Département Gironde",
    "link": "https://www.gironde.fr/acteurs-jeunesse/les-actions/aide-departementale-au-permis-de-conduire",
    "amount": 75,
    "unit": "%",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "33"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  },
  {
    "id": "departement_cotes_d_armor-aide-departementale-au-permis-de-conduire-passengagement",
    "slug": "departement_cotes_d_armor-aide-departementale-au-permis-de-conduire-passengagement",
    "label": "Aide départementale au permis de conduire : Pass'Engagement",
    "description": "Le département des Côtes d'Armor propose aux jeunes de s'engager bénévolement dans une association ou un centre social à raison de 2 heures minimum par semaine, en échange de l'octroi d'une bourse pour soutenir un projet personnel ou professionnel. Ce dispositif peut être demandé",
    "institution": "Département des Côtes d'Armor",
    "link": "https://cotesdarmor.fr/pass-engagement",
    "amount": 1200,
    "unit": "€",
    "periodicite": "autre",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "22"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  },
  {
    "id": "caf-ain-aide-bafa-session-generale",
    "slug": "caf-ain-aide-bafa-session-generale",
    "label": "aide locale au BAFA pour une session de formation générale",
    "description": "La CAF de l'Ain vous aide à financer votre session de formation générale, en complément de l'aide apportée par la CNAF. L'aide est versée pour tous les demandeurs sans conditions de ressources, directement à l'organisme de formation qui la déduit du coût du stage.",
    "institution": "CAF de l'Ain",
    "link": "https://www.caf.fr/allocataires/caf-de-l-ain/offre-de-service/vie-professionnelle/vous-accompagner-pour-passer-le-bafa",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "01"
        ]
      }
    ]
  },
  {
    "id": "caf-savoie-aide-bafa",
    "slug": "caf-savoie-aide-bafa",
    "label": "aide locale au BAFA pour une session de formation générale",
    "description": "L'aide à la formation du BAFA est une aide locale mise à disposition par la CAF de la Savoie pour vous aider à financer votre session de formation générale en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF de la Savoie",
    "link": "https://caf.fr/allocataires/caf-de-la-savoie/offre-de-service/vie-professionnelle/les-aides-la-formation-au-bafa-bafd#aidelocale",
    "amount": 350,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "73"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      }
    ]
  },
  {
    "id": "caf-aide-nationale-bafa",
    "slug": "caf-aide-nationale-bafa",
    "label": "aide nationale au Brevet d'aptitude aux fonctions d'animateur (BAFA)",
    "description": "La CAF vous aide à financer une partie de votre BAFA afin d'obtenir une formation qualifiante d’animateur. <br>Les étapes de la formation du BAFA sont les suivantes : <br>1) la session de formation générale, <br>2) le stage pratique, <br>3) la session d’approfondissement ou de qu",
    "institution": "Caisse d’allocations familiales",
    "link": "https://www.service-public.fr/particuliers/actualites/A16188",
    "amount": 200,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      }
    ]
  },
  {
    "id": "departement-aude-aide-personnalisee-retour-emploi-mobilite",
    "slug": "departement-aude-aide-personnalisee-retour-emploi-mobilite",
    "label": "aide personnalisée au retour à l'emploi - Mobilité",
    "description": "Le Département aide les jeunes qui perçoivent le revenu de solidarité active (RSA) dans le financement de leur permis de conduire. Cette aide est soumise à l'évaluation sociale du centre médico-social référent.",
    "institution": "Département Aude",
    "link": "https://www.aude.fr/annuaire-des-aides-au-permis-pour-les-jeunes/aide-personnalisee-au-retour-emploi-apre-mobilite",
    "amount": 500,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "11"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  },
  {
    "id": "caf-yvelines-aide-bafa-generale",
    "slug": "caf-yvelines-aide-bafa-generale",
    "label": "Aides au BAFA et au BAFD",
    "description": "Les aides à la formation au BAFA et BAFD sont des aides locales mise à disposition par la CAF des Yvelines pour vous aider à financer vos sessions en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF des Yvelines",
    "link": "https://caf.fr/allocataires/caf-des-yvelines/offre-de-service/vie-professionnelle/l-aide-au-bafa-et-au-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "78"
        ]
      }
    ]
  },
  {
    "id": "caf-tarn-aide-bafa-approfondissement",
    "slug": "caf-tarn-aide-bafa-approfondissement",
    "label": "aides au BAFA pour une session de formation générale ou d'approfondissement",
    "description": "Les aides à la formation du BAFA sont des aides locales mise à disposition par la CAF du Tarn pour vous aider à financer votre session générale ou d’approfondissement/perfectionnement, en complément de l'aide nationale apportée par la CAF.",
    "institution": "CAF du Tarn",
    "link": "https://www.caf.fr/allocataires/caf-du-tarn/offre-de-service/vie-professionnelle/bafa-bafd",
    "amount": 300,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 16
      },
      {
        "type": "departements",
        "values": [
          "81"
        ]
      }
    ]
  },
  {
    "id": "caf-meurthe-et-moselle-aide-bafa-bafd",
    "slug": "caf-meurthe-et-moselle-aide-bafa-bafd",
    "label": "aides aux formations BAFA et BAFD",
    "description": "Les aides aux formations BAFA et BAFD sont mises à disposition par la CAF de Meurthe-et-Moselle pour aider les jeunes à financer une partie de leurs stages, en complément de l'aide nationale apportée par la CAF. Seuls les stagiaires qui suivent une formation complète, du stage de",
    "institution": "CAF de Meurthe-et-Moselle",
    "link": "https://www.caf.fr/allocataires/caf-de-meurthe-et-moselle/offre-de-service/vie-personnelle/les-aides-aux-formations-bafa-et-bafd",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": ">=",
        "value": 17
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 25
      },
      {
        "type": "departements",
        "values": [
          "54"
        ]
      }
    ]
  },
  {
    "id": "departement_ain_carte_jeunes",
    "slug": "departement_ain_carte_jeunes",
    "label": "carte jeunes 01 pour le sport, la culture et les loisirs",
    "description": "La Carte Jeunes 01 est un porte-monnaie en ligne offert à tous les collégiens par le département de l'Ain, avec 25 euros pour les activités culturelles, 25 euros pour les activités sportives et de loisirs, plus de 170 euros d'offres promotionnelles, ainsi que des bons plans chez ",
    "institution": "Département Ain",
    "link": "https://www.ain.fr/solutions/carte-jeunes-01/",
    "amount": 50,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "01"
        ]
      }
    ]
  },
  {
    "id": "union_europeenne_discovereu",
    "slug": "union_europeenne_discovereu",
    "label": "DiscoverEU",
    "description": "DiscoverEU est une action du programme Erasmus+ qui donne l’occasion aux jeunes âgés de 18 ans de voyager et d’explorer la diversité de l’Europe. 40 000 jeunes européens recevront un titre de transport leur permettant de voyager gratuitement pendant 30 jours dans toute l’Europe e",
    "institution": "L'Union européenne",
    "link": "https://youth.europa.eu/discovereu_fr",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "age",
        "operator": "=",
        "value": 18
      }
    ]
  },
  {
    "id": "departement_aude-aide-departementale-au-permis-de-conduire",
    "slug": "departement_aude-aide-departementale-au-permis-de-conduire",
    "label": "fonds d'aide aux jeunes mobilité",
    "description": "Le Département aide les jeunes qui ont des problèmes financiers ou d’insertion et qui ont un projet professionnel (contrat d’apprentissage, emploi, stage…) à financer leur permis de conduire. Pour effectuer une demande, vous devez être accompagné par un·e référent·e de l'une des ",
    "institution": "Département Aude",
    "link": "https://www.aude.fr/annuaire-des-aides-au-permis-pour-les-jeunes/fonds-aide-aux-jeunes-faj-mobilite",
    "amount": 500,
    "unit": "€",
    "periodicite": "ponctuelle",
    "source": "javascript",
    "conditions": [
      {
        "type": "departements",
        "values": [
          "11"
        ]
      },
      {
        "type": "age",
        "operator": ">=",
        "value": 18
      },
      {
        "type": "age",
        "operator": "<=",
        "value": 25
      }
    ]
  }
] as const;
